- name: install httpd 
  hosts: web
  become: yes
  tasks:
    - name: install httpd package
      community.general.apache2_module:
        name: httpd
        state: present
    - name: start httpd service
      community.general.apache2_module:
        state: started
        enabled: yes
