- name: install httpd 
  hosts: web
  become: yes
  tasks:
    - name: Enable the Apache2 module wsgi
      community.general.apache2_module:
        state: present
        name: wsgi
    - name: start httpd service
      ansible.builtin.service:
        state: started
        enabled: yes
