- name: install httpd 
  hosts: web
  become: yes
  tasks:
    - name: install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: present
    - name: start httpd service
      ansible.builtin.service:
        state: started
        enabled: yes
